### PR TITLE
Inlcude challenge password attribute if required by EST server

### PR DESCRIPTION
**Pull request by mobe1**
The changes introduced come after an [issue/feature request](https://github.com/globalsign/est/issues/30) has been opened.
They allow us to enroll a CSR that includes the TLS-unique value as recommended by the RFC 7030

- Because each http client instantiation results in a new TLS-unique, one way of including it would be to make EST requests from the same http client.
- Because the standard crypto/x509 Go package does not handle the challenge password attribute (OID) the way an EST/CA server expects it, the CSR creation had to be wrapped.

### CODE REVIEW

**Comment by mobe1** [comment]
There has been a `git branch filter` command applied which accounts for all git history commits being displayed...

**Comment by mobe1** [comment]
PR is closed : once the PR is "clean" enough, new PR will be created.

**Comment by toddgaunt-gs** [comment]
Thank you for the contribution, yes a cleaner version would be great :)!

**Comment by DDvO** [comment]
Just a note: the follow-up on this PR is in #38.

**Pull request closed without merging**
